apiVersion: v1
kind: Service
metadata:
  labels:
    app: backendservice
  name: backendservice
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: backendservice
  type: ClusterIP